language: php

php:
  - 5.3
  - 5.4

before_script: 
  - composer install --dev
script: vendor/bin/phpunit

matrix:
  allow_failures:
    - branches:
        except:
          - master
          - stable
          - development
